server:
  port: 8082
spring:
#  datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf-8
    username: root
    password: 123456


#  Redis
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mtbatis.demo.mapper



